[project]
name = "get_movie_info"
version = "0.1.0"
description = "Simple movie review tool using OMDb Open Movie Database"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastmcp>=2.11.0",
    "requests>=2.32.3",
]
